AWSTemplateFormatVersion: 2010-09-09
Description:  AWS Playground - Creating The Instance Role whose credentials will leak
Metadata:
  LICENSE: Apache License Version 2.0
Resources:
  PrivateBucket1: 
    Type: AWS::S3::Bucket     
