AWSTemplateFormatVersion: 2010-09-09
Description:  AWS Playground - Creating Bucket Forcing SSE
Metadata:
  LICENSE: Apache License Version 2.0
Mappings:
  Application:
    Settings:
      AvailabilityZoneA: 'us-east-1a'
      AvailabilityZoneB: 'ap-southeast-1'
      UniqueSuffix: 'revoke-credentials'
Parameters:  
  BucketSuffix: 
    AllowedPattern: ^[\d\w]{3,}$
    Type: String
    Description: At least three digits for uniqueness 
Resources:
  #===== Bucket creation with bucket rejecting non encrypted puts
  HelloBucketSource: 
    Type: 'AWS::S3::Bucket'
    Properties: 
      AccessControl: Private
      BucketEncryption: 
        ServerSideEncryptionConfiguration:   
          - ServerSideEncryptionByDefault: 
              SSEAlgorithm: 'AES256'
      BucketName: !Sub
        - 'playground-bucket-${BucketSuffix}-${UniqueSuffix}'
        - UniqueSuffix: !FindInMap [ Application, Settings, UniqueSuffix ]
      VersioningConfiguration: 
        Status: 'Enabled'
  BucketPolicyCredentials:  
    Type: 'AWS::S3::BucketPolicy'  
    Properties:  
      Bucket:  
        Ref: "HelloBucketSource"  
      PolicyDocument:  
        Statement:  
        -  
          Sid: "DenyIncorrectEncryptionHeader"  
          Action:  
            - "s3:PutObject"  
          Effect: "Deny"  
          Resource:  
            Fn::Join:  
              - ""  
              -  
                - "arn:aws:s3:::"  
                -  
                  Ref: "HelloBucketSource"  
                - "/*"  
          Principal: "*"  
          Condition:  
            StringNotEquals:  
              s3:x-amz-server-side-encryption:  
                - "AES256"  
        -  
          Sid: "DenyUnencryptedObjectUploads"  
          Action:  
            - "s3:PutObject"  
          Effect: "Deny"  
          Resource:  
            Fn::Join:  
              - ""  
              -  
                - "arn:aws:s3:::"  
                -  
                  Ref: "HelloBucketSource"  
                - "/*"  
          Principal: "*"  
          Condition:  
            "Null":  
              s3:x-amz-server-side-encryption:  
                - "true"    
    